### ISSUE TITLE
Skapa återvinningslexikon/sorteringsguide

### ISSUE THREAD

**Issue by mcedvin** [mcedvin/PVT#7]

**Comment by hi-tech-jazz** [comment]
Här är FTI:s sorteringsguide som vi kan använda: https://www.ftiab.se/sortering.html

**Comment by hi-tech-jazz** [comment]
Den här verkar också bra: https://www.sopor.nu

**Comment by LovisaFff** [comment]
Den här finns också, på engelska dock
https://earth911.com/recycling-center-search-guides/
